#!/usr/bin/env python3
"""Regenerate the Lea wordmark from the IBM Plex Mono subset.

The wordmark is "Lea" set in IBM Plex Mono SemiBold. Rather than ask every
surface to load the webfont, the glyphs are outlined once into a path that the
header, the favicon and the README all share. Run this only when the typeface,
the weight or the ramp changes:

    uvx --with brotli --from fonttools python scripts/build-wordmark.py

It rewrites lib/wordmark.mjs and the two README images in assets/img/.
"""

from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "assets" / "fonts" / "ibm-plex-mono-600-lea.woff2"
WORD = "Lea"
PAD = 24  # em units of air around the ink

# The brand ramp: blue into teal into the green the app uses for "proved", and
# the same ramp lifted for dark backgrounds.
RAMPS = {
    "light": [("0", "#2f5aa8"), (".32", "#128a8a"), (".62", "#16733d"), ("1", "#0d4f2b")],
    "dark": [("0", "#9dbcf0"), (".32", "#74d3c9"), (".62", "#7cc79c"), ("1", "#b5e3c6")],
}


def outline():
    """Return (path data, viewBox) for the word, y flipped into SVG space."""
    font = TTFont(FONT)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    bounds = BoundsPen(glyphs)
    parts, x = [], 0

    for char in WORD:
        name = cmap[ord(char)]
        # Font units are y-up and SVG is y-down, so mirror as we lay each glyph
        # out on its advance width.
        flip = Transform(1, 0, 0, -1, x, 0)
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen, flip))
        glyphs[name].draw(TransformPen(bounds, flip))
        parts.append(pen.getCommands())
        x += font["hmtx"][name][0]

    x0, y0, x1, y1 = bounds.bounds
    view_box = f"{x0 - PAD:.0f} {y0 - PAD:.0f} {x1 - x0 + 2 * PAD:.0f} {y1 - y0 + 2 * PAD:.0f}"
    return " ".join(parts), view_box


def ramp_literal(name, stops):
    rows = "\n".join(f'  ["{offset}", "{color}"],' for offset, color in stops)
    return f"export const {name} = [\n{rows}\n];"


def write_module(path_data, view_box):
    module = f'''/**
 * The Lea wordmark: "Lea" set in IBM Plex Mono SemiBold and outlined to paths,
 * so the mark renders identically in the header, the favicon and the README
 * without any of them depending on the webfont having loaded.
 *
 * Generated by scripts/build-wordmark.py — edit that, not this.
 */

/** Glyph outlines on a 1000-unit em, laid out on their advance widths. */
export const WORDMARK_PATH =
  "{path_data}";

/** Tight box around the ink, with a little air. */
export const WORDMARK_VIEWBOX = "{view_box}";

/** The brand ramp: blue into teal into the green the app uses for "proved". */
{ramp_literal("RAMP_LIGHT", RAMPS["light"])}

/** The same ramp lifted for dark backgrounds. */
{ramp_literal("RAMP_DARK", RAMPS["dark"])}

/** A `<linearGradient>` carrying one of the ramps, angled like the CSS one. */
export function rampDef(id, stops) {{
  const inner = stops.map(([o, c]) => `<stop offset="${{o}}" stop-color="${{c}}"/>`).join("");
  return `<linearGradient id="${{id}}" x1="0" y1="0" x2="1" y2=".58">${{inner}}</linearGradient>`;
}}
'''
    target = ROOT / "lib" / "wordmark.mjs"
    target.write_text(module)
    print(f"wrote {target.relative_to(ROOT)}")


def write_images(path_data, view_box):
    for name, stops in RAMPS.items():
        defs = "\n    ".join(f'<stop offset="{o}" stop-color="{c}"/>' for o, c in stops)
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" width="360" role="img" aria-label="Lea">
  <title>Lea</title>
  <!-- IBM Plex Mono SemiBold, outlined so the mark needs no webfont. -->
  <linearGradient id="ramp" x1="0" y1="0" x2="1" y2=".58">
    {defs}
  </linearGradient>
  <path fill="url(#ramp)" d="{path_data}"/>
</svg>
'''
        target = ROOT / "assets" / "img" / f"lea-wordmark-{name}.svg"
        target.write_text(svg)
        print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    data, box = outline()
    write_module(data, box)
    write_images(data, box)
